# Generated by Django 4.0.1 on 2022-07-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_age_remove_user_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile_number'),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
    ]
