# Generated by Django 4.0.1 on 2022-08-09 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_package', models.CharField(blank=True, max_length=255, null=True, verbose_name='departure_package')),
                ('return_package', models.CharField(blank=True, max_length=255, null=True, verbose_name='return_package')),
                ('departure_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='departure_price')),
                ('return_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='return_price')),
                ('departure_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='departure_time')),
                ('return_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='return_time')),
                ('date_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_from')),
                ('date_to', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_to')),
                ('departure_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='departure_from')),
                ('departure_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='departure_to')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name='location_to')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='location_to')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='mobile_number')),
                ('province', models.CharField(blank=True, max_length=255, null=True, verbose_name='province')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='city')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
                ('barangay', models.CharField(blank=True, max_length=255, null=True, verbose_name='barangay')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
