# Generated by Django 4.0.1 on 2022-09-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ticket_type'),
        ),
    ]
