# Generated by Django 4.0.1 on 2022-08-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefrom', models.CharField(blank=True, max_length=255, null=True, verbose_name='timefrom')),
                ('timeto', models.CharField(blank=True, max_length=255, null=True, verbose_name='timeto')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price')),
                ('package_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='package_name')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
